name: 酷狗
on:
  schedule:
    - cron: '10 0,8,16 * * *'
jobs:
  task:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Java 环境
      - name: 设置Java环境
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      # 运行
      - name: 运行jar包
        env:
          KG_CONFIG: ${{secrets.KG_CONFIG}}
        run: java -jar kugou-1.0-SNAPSHOT-all.jar
