name: 腾讯自选股
on:
  schedule:
    # 0 => 8 4 => 12 6=> 14 10 => 18 12 => 20
    - cron: '10 0 * * *'
jobs:
  task:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Java 环境
      - name: 设置Java环境
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      # 运行
      - name: 运行腾讯自选股jar包
#         env:
#           KG_CONFIG: ${{secrets.KG_CONFIG}}
        run: java -jar txzxg-1.0-SNAPSHOT-all.jar
