name: 九章头条-Branch
on:
#   push:
#     branches: [ task_kugou ]
#   pull_request:
#     branches: [ task_kugou ]
  schedule:
    - cron: '30 12 * * *'
    
jobs:
  task:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Java 环境
      - name: 设置Java环境
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: 开始执行脚本
        run: echo "九章头条 task_jztt 分支空执行"
      # 运行
      - name: 运行jar包
#         env:
#           JZTT_CONFIG: ${{secrets.JZTT_CONFIG}}
#         run: java -jar jztt-1.0-SNAPSHOT-all.jar
