name: 中青看点
on:
  schedule:
    # 0 => 8 10 => 18 
    - cron: '1 0,10, * * 1'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  task:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Java 环境
      - name: 设置Java环境
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      # 运行
      - name: 开始执行脚本,运行jar包
        env:
          ZQKD_CONFIG: ${{secrets.ZQKD_CONFIG}}
        run: java -jar zqkd-1.0-SNAPSHOT-all.jar
