name: zw酷狗
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # 0 => 8 4 => 12 6=> 14 10 => 18 12 => 20
    - cron: '10 0,5,10 * * *'
jobs:
  task:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Java 环境
      - name: 设置Java环境
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      # 运行
      - name: 运行jar包
        env:
          ZW_KG_CONFIG: ${{secrets.ZW_KG_CONFIG}}
        run: java -jar kugou-1.0-SNAPSHOT-all.jar
